---
title: "dataGenerato.R"
author: "Maia Cossette"
date: "2025-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#1 Creating a species vector and randomly sample it 100 times
```{r}

set.seed(1)
species<- c("cat", "dog", "whale", "dolphin", "shark")
sample(species, size = 100, replace = TRUE)
```

#2 Creating a width vector and using a log distribution to avoid negatives or zeros
```{r}
set.seed(1)
Limb_width<- c(1:100)
rlnorm(100, meanlog = 0, sdlog =1)

```


#3 Created a length vector and used a normal distribution 
```{r}
set.seed(1)
Limb_length<- rnorm(100, mean = 50, sd = 10)
Limb_length
```

#4 Created a names vector with 100 sample
```{r}
set.seed(1)
Observer<- c("Maia", "Peter", "Jade")
Observers<- sample(Observer, size = 100, replace = TRUE)
Observers

```

#5 Created a data frame with all the vectors and turned it into csv file
```{r}
measurements.csv<-data.frame(species, Limb_width, Limb_length, Observers)
write.csv(measurements.csv,file= "measurements.csv", row.names = F)
head(measurements.csv)
```
